# fly.toml app configuration file generated for soulcandy2 on 2025-03-07T01:59:24+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'soulcandy2'
primary_region = 'sjc'
console_command = '/rails/bin/rails console'

[build]

[deploy]
  release_command = './bin/rails db:prepare'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'

[[statics]]
  guest_path = '/rails/public'
  url_prefix = '/'
